# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
    
- task: safeer-accuknox-iac@0.1.11
  inputs:
    accuknoxEndpoint: 'cspm.demo.accuknox.com'
    accuknoxTenantId:  '$(tentant-id)'
    accuknoxToken: ' $(accuknox-token)'
    accuknoxLabel: 'test'
    inputQuiet: true
    inputCompact: true