# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Test

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
    
- task: subinoyworks-accuknox-iac@0.1.21
  inputs:
    accuknoxEndpoint: '$(accuknox-enpoint)'
    accuknoxTenantId: '1111'
    accuknoxToken: '$(accuknox-token)'
    accuknoxLabel: '$(accuknox-label)'
    inputQuiet: true
    inputCompact: true